zookeeper:
  image: ryanratcliff/zookeeper
  ports: 
    - "2181:2181"
  container_name: zookeeper
kafka:
  image: ryanratcliff/kafka
  links:
    - zookeeper:zookeeper
  ports:
    - "9092:9092"
  container_name: kafka
redis:
  image: ryanratcliff/redis
  ports:
    - "6379:6379"
  container_name: redis
dynamodb:
  image: ryanratcliff/dynamodb
  ports:
    - "8000:8000"
  container_name: dynamodb

